# Generated by Django 3.2.7 on 2021-09-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210906_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='song',
            field=models.CharField(default='default val', max_length=80),
            preserve_default=False,
        ),
    ]
