# Generated by Django 3.2.19 on 2023-07-16 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='song',
        ),
    ]
