# Generated by Django 3.2.7 on 2021-12-15 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0006_albumid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlbumID',
        ),
    ]
