# Generated by Django 3.2.18 on 2023-03-03 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0008_favalbums'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favalbums',
            options={'verbose_name_plural': 'Fav albums'},
        ),
    ]
