# Generated by Django 3.2.19 on 2023-07-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0009_alter_favalbums_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favalbums',
            name='a0',
            field=models.CharField(blank=True, max_length=22),
        ),
        migrations.AlterField(
            model_name='favalbums',
            name='a1',
            field=models.CharField(blank=True, max_length=22),
        ),
        migrations.AlterField(
            model_name='favalbums',
            name='a2',
            field=models.CharField(blank=True, max_length=22),
        ),
        migrations.AlterField(
            model_name='favalbums',
            name='a3',
            field=models.CharField(blank=True, max_length=22),
        ),
        migrations.AlterField(
            model_name='favalbums',
            name='a4',
            field=models.CharField(blank=True, max_length=22),
        ),
        migrations.AlterField(
            model_name='favalbums',
            name='a5',
            field=models.CharField(blank=True, max_length=22),
        ),
    ]
