# Generated by Django 3.2.19 on 2023-07-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='album',
            field=models.TextField(blank=True, max_length=32),
        ),
    ]
