# Generated by Django 3.2.21 on 2023-10-09 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='album',
            new_name='spotify_release_uri',
        ),
    ]
