# Generated by Django 3.2.7 on 2021-09-27 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spotify', '0002_remove_spotifytoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytoken',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spotify_token', to=settings.AUTH_USER_MODEL),
        ),
    ]
