# Generated by Django 3.2.7 on 2021-12-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_rename_expires_in_spotifytoken_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.CharField(max_length=22)),
            ],
        ),
    ]
