# Generated by Django 3.2.7 on 2022-04-02 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile'),
        ('spotify', '0007_delete_albumid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavAlbums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a0', models.CharField(max_length=22)),
                ('a1', models.CharField(max_length=22)),
                ('a2', models.CharField(max_length=22)),
                ('a3', models.CharField(max_length=22)),
                ('a4', models.CharField(max_length=22)),
                ('a5', models.CharField(max_length=22)),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
