# Generated by Django 3.2.21 on 2023-09-27 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20230916_2105'),
        ('spotify', '0010_auto_20230708_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favalbums',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_albums', to='users.profile'),
        ),
    ]
