# Generated by Django 3.2.21 on 2023-10-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0011_alter_favalbums_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favalbums',
            options={'verbose_name_plural': 'favorite albums'},
        ),
        migrations.AlterField(
            model_name='spotifytoken',
            name='access_token',
            field=models.TextField(),
        ),
    ]
