# Generated by Django 3.2.7 on 2022-02-12 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220212_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
