# Generated by Django 3.2.21 on 2023-09-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='first',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last',
        ),
        migrations.AddField(
            model_name='profile',
            name='first',
            field=models.CharField(default='Not specified', max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='last',
            field=models.CharField(default='Not specified', max_length=64),
        ),
    ]
