# Generated by Django 3.2.21 on 2023-10-31 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='test',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
