# Generated by Django 3.2.21 on 2023-10-31 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='test',
        ),
    ]
